config/routes.rb
WCP::Application.routes.draw do 

  resources :blueprints do
    post :add_step
    get :resort_steps
    post :delete_step
  end

  match "login" => "login#login", :as => :login
  match "login/missing_password"
  post "login/logout", :as => :logout
  
  get "account" => "account#index", :as => :account

  match "account/update", :as => :account_update

  get 'company' => 'company#index', :as => :company_config
  post 'company/update' => 'company#update', :as => :company_config_update

  resources :companies

  match 'dashboard(/:action)' => 'dashboard', :as => :dashboard

  root :to => "dashboard#index" 

  resources :machine_blueprints, :except => [ :show ]

  resources :clouds do
    post :reset
  end
  resources :deployments do
    collection do
      post :cleanup
    end
  end

  resources :machines, :except => [ :new, :create ]  do
    collection do 
      post :cleanup
    end
  end

  resources :machines
end

app/models/blueprint.rb
class Blueprint < BaseModel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :blueprint_options_data, :type => Hash, :default => {}

  validates_presence_of :name

  has_many :blueprint_steps

  def initialize_step(step_data)
    if !step_data.initialized?
      self.steps[step_data.step].initialize_step_data(step_data)
    end
    step_data
  end

  class Options < HashModel

  end

  def blueprint_parameters
    self.steps.inject([]) do |elems,step|
      elems + step.step_class_object.blueprint_parameters
    end.uniq
  end

  def parameters
    self.steps.inject([]) do |elems,step|
      elems + step.step_class_object.deployment_parameters
    end.uniq
  end

  def blueprint_parameters_list
    self.blueprint_parameters.map { |elm| elm[0] }
  end

  def parameters_list 
    self.parameters.map { |elm| elm[0] }
  end

  def blueprint_options=(val)
    self.blueprint_options_data = blueprint_options(val).to_hash
  end

  def blueprint_options(opts=nil)
     opts = Options.new(opts || blueprint_options_data)
     opts.additional_vars(self.blueprint_parameters_list)
     opts
  end

  def config(opts)
    opts = Options.new(opts)
    opts.additional_vars(self.parameters_list)
    opts
  end

 def add_step(name,step_class_name)
    
    self.reload
    cls = step_class_name.constantize

    original_blueprint_step_hash = nil

    next_position = self.steps[-1] ? self.steps[-1].position + 1 : 0
    substeps = cls.step_info_details[:substeps]
    (0..substeps-1).each do |substep|
      step = BlueprintStep.create(:name => name,
                            :position => next_position,
                            :identity_hash => original_blueprint_step_hash,
                            :substep => substep,
                            :blueprint_id => self.id,
                            :step_class_name => step_class_name,
                            :step_options_class_name => cls.step_info_details[:options])

      if original_blueprint_step_hash.blank?
        original_blueprint_step_hash = "STEP#{step.id.to_s}"
        step.update_attributes(:identity_hash => original_blueprint_step_hash)
      end
      next_position += 1
    end
    self.reload
  end

 def finished?(step_number)
   step_number >= self.steps.length
 end
  
  def step_finished?(step_data)
    self.steps[step_data.step].finished?(step_data)
  end

  def execute_step!(step_data)
    if step_data.step > self.steps.length
      return false
    else
      self.steps[step_data.step].execute!(step_data)
    end
  end

  def machine_failed!(step_data,machine)
    self.steps[step_data.step].machine_failed!(step_data,machine)
  end

  def machine_activated!(step_data,machine)
    self.steps[step_data.step].machine_activated!(step_data,machine)
  end

  def resort_steps!
    self.steps.each_with_index do |step,idx|
      step.update_attributes(:position => idx + 1)
    end

  end

  def steps
    self.blueprint_steps.sort { |a,b| a.position <=> b.position }
  end
  
end

app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController

  current_tab 'Blueprints'

  # GET /blueprints
  # GET /blueprints.xml
  def index
    @blueprints = Blueprint.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @blueprints }
    end
  end

  # GET /blueprints/1
  # GET /blueprints/1.xml
  def show
    @blueprint = Blueprint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @blueprint }
    end
  end

  # GET /blueprints/new
  # GET /blueprints/new.xml
  def new
    @blueprint = Blueprint.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blueprint }
    end
  end


  def add_step
    @blueprint = Blueprint.find(params[:blueprint_id])

    if full_class = BlueprintStep.check_step_identifier(params[:step_class])
      @blueprint.add_step(params[:name],full_class)
    end

    @blueprint.reload
    
    render :partial => 'blueprint_steps'
  end


  def resort_steps
    @blueprint = Blueprint.find(params[:blueprint_id])

    @steps = @blueprint.blueprint_steps

    (params['step_id']||[]).each_with_index do |step_id,position|
       step = @steps.detect { |s| s.id.to_s == step_id} 
       step.update_attributes(:position => position) if step
    end

    @blueprint.reload
     
    render :partial => 'blueprint_steps'
  end


  def delete_step
    @step = BlueprintStep.find(params[:step_id])
    @step.destroy

    @blueprint = Blueprint.find(params[:id])
    @blueprint.resort_steps!

    render :partial => 'blueprint_steps'
  end

  # GET /blueprints/1/edit
  def edit
    @blueprint = Blueprint.find(params[:id])
  end

  # POST /blueprints
  # POST /blueprints.xml
  def create
    @blueprint = Blueprint.new(params[:blueprint])

    respond_to do |format|
      if @blueprint.save
        format.html { redirect_to(@blueprint, :notice => 'Blueprint was successfully created.') }
        format.xml  { render :xml => @blueprint, :status => :created, :location => @blueprint }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @blueprint.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blueprints/1
  # PUT /blueprints/1.xml
  def update
    @blueprint = Blueprint.find(params[:id])

    respond_to do |format|
      if @blueprint.update_attributes(params[:blueprint])
        format.html { redirect_to(blueprint_path(@blueprint), :notice => 'Blueprint was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blueprint.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blueprints/1
  # DELETE /blueprints/1.xml
  def destroy
    @blueprint = Blueprint.find(params[:id])
    @blueprint.destroy

    respond_to do |format|
      format.html { redirect_to(blueprints_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper
end

app/views/blueprints/_blueprint_steps.html.haml
- @blueprint.steps.each do |step|
  %li.line_item{:id => "#blueprint_step_#{step.id}"}
    %span.blueprint_name= "##{step.position} #{step.name}"
    %span.blueprint_description= "#{step.step_name} (#{step.substep})"
    %a{:href => 'javascript:void(0);',  :onclick => "Blueprint.removeStep('#{step.id}')"}
      x

app/views/blueprints/_form.html.haml
= semantic_form_for(@blueprint, :as => :blueprint) do |f|
  = f.semantic_errors
  = f.inputs do 
    = f.input :name
  - if @blueprint.id
    = render :partial => 'parameters'
  = f.buttons do
    = f.commit_button "Submit"

app/views/blueprints/_parameters.html.haml
= semantic_fields_for 'blueprint[blueprint_options]', @blueprint.blueprint_options do |f|
  = f.inputs do
    - @blueprint.blueprint_parameters.each do |param|
      = f.input param[0], (param[1].is_a?(Hash) ? param[1] : param[1].call)

app/views/blueprints/edit.html.haml
%h1 Editing blueprint
= render 'form'
= link_to 'Show', blueprint_path(@blueprint)
|
= link_to 'Back', blueprints_path

app/views/blueprints/index.html.haml
%h1 Listing blueprints
.action_links
  = link_to 'New Blueprint', new_blueprint_path
%table.main_table
  %tr
    %th Name (Click to Edit Steps)
    %th Edit Options
    %th Destroy
  - @blueprints.each do |blueprint|
    %tr
      %td= link_to blueprint.name, blueprint_path(blueprint)
      %td= link_to 'Edit', edit_blueprint_path(blueprint)
      %td= link_to 'Destroy', blueprint_path(blueprint), :confirm => 'Are you sure?', :method => :delete
%br/

app/views/blueprints/new.html.haml
%h1 New blueprint
= render 'form'
= link_to 'Back', blueprints_path

app/views/blueprints/show.html.haml
:javascript
  Blueprint = {
    addStep: function() { 
      var name =  $('#options_step_name').val();
      var step_class = $('#options_add_step').val();
      if(step_class=='' || name=='') {
        alert('Please enter a name and a step class');
      } else {
        $("#blueprint_steps").load('#{blueprint_add_step_url(@blueprint)}',{name:name,step_class:step_class})
      }
    },

    createSortables: function() {
      $('#blueprint_steps').sortable({
        update : function () { 
          var order = $('#blueprint_steps').sortable('serialize', { key: 'step_id[]' }); 
          $("#blueprint_steps").load('#{blueprint_resort_steps_url(@blueprint)}',order);
        } 

      }
      );
         $('#blueprint_steps').disableSelection();
    },

    removeStep: function(step_id) {
       if(confirm('Remove this step')) {
        var remove_steps = { step_id: step_id };
        $('#blueprint_steps').load('#{blueprint_delete_step_url(@blueprint)}',remove_steps);
       }
    }

  }

  $(function() { Blueprint.createSortables(); });
%h1= @blueprint.name

.add_step
  = text_field_tag(:options_step_name,'',:size => 20)
  = select_tag(:options_add_step, options_for_select([[]] + BlueprintStep.available_step_options))
  %button{:onclick => "Blueprint.addStep()"}
    Add Steps

%ul#blueprint_steps
  = render 'blueprint_steps'

= link_to 'Edit', edit_blueprint_path(@blueprint)
|
= link_to 'Back', blueprints_path