config/routes.rb
WCP::Application.routes.draw do 

  resources :blueprints do
    post :add_step
    get :resort_steps
    post :delete_step
  end

  match "login" => "login#login", :as => :login
  match "login/missing_password"
  post "login/logout", :as => :logout
  
  get "account" => "account#index", :as => :account

  match "account/update", :as => :account_update

  get 'company' => 'company#index', :as => :company_config
  post 'company/update' => 'company#update', :as => :company_config_update

  resources :companies

  match 'dashboard(/:action)' => 'dashboard', :as => :dashboard

  root :to => "dashboard#index" 

  resources :machine_blueprints, :except => [ :show ]

  resources :clouds do
    post :reset
  end
  resources :deployments do
    collection do
      post :cleanup
    end
  end

  resources :machines, :except => [ :new, :create ]  do
    collection do 
      post :cleanup
    end
  end

  resources :machines
end

app/models/machine_blueprint.rb
class MachineBlueprint < BaseModel
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :machines

  field :name
  field :identifier

  field :launcher_class

  field :instance_type
  field :login_user, :default => 'ubuntu'

  field :options_data, :type => Hash, :default => {}

  before_save :set_instance_type

  has_options :instance_type, [["EC2 Server", "ec2"],["Load Balancer","balancer"],["Database","rds"]]

  validates :name, :presence => true
  validates :identifier, :format =>  { :with => /^[a-zA-Z\-_0-9]+$/ }
  
  has_options :instance_type, Machine.instance_type_original_options
  
  def launcher
     @launcher ||= self.launcher_class.camelcase.constantize
  end

  class Options < HashModel

  end

  def parameters
    launcher.machine_parameters.uniq
  end

  def parameters_list
    parameters.map { |elm| elm[0] }
  end

  def config(opts=nil)
    return @options_object if @options_object && !opts
    @options_object = Options.new(opts || self.options_data)
    @options_object.additional_vars(self.parameters_list)
    @options_object
  end

  def config=(val)
    self.options_data = config(val).to_hash
  end


  def launcher_name
    launcher.machine_launcher_name
  end

  def launcher_description 
    launcher.description(self)
  end

  def launcher_instance_type
    launcher.machine_launcher_options[:instance_type] || 'ec2'
  end
   
  def self.fetch(identifier)
    self.where(:identifier => identifier).first
  end
  
  def self.select_options(elements=nil)
    (elements||self.all).map { |b| [ b.name,b.identifier ] }
  end

  def self.rds_select_options
    self.select_options(self.all.select { |b| b.instance_type == 'rds' })
  end

  def self.rds_server_select_options
    self.select_options(self.all.select { |b| b.launcher.to_s == "Machines::RdsServer" })
  end

  def self.rds_restore_select_options
    self.select_options(self.all.select { |b| b.launcher.to_s == "Machines::RdsServerSnapshot" })
  end

  def self.ec2_select_options
    self.select_options(self.all.select { |b| b.instance_type == 'ec2' })
  end

  def self.elb_select_options
    self.select_options(self.all.select { |b| b.instance_type == 'balancer' })
  end

 def self.machine_directories
    [ Rails.root.join("app/plans/machines/*") ]
  end


  def self.launcher_class_options
    opts = []
    machine_directories.each do |dir|
      Dir.glob(dir).each do |filepath|
        if File.extname(filepath)== '.rb'
          fl = (filepath.gsub((dir.to_s+"/").gsub("/*",""),"")).gsub(/\.rb$/,'')
          if fl != "base" 
            cls = "Machines::#{fl.camelcase}"
            opts << [ cls.constantize.machine_launcher_name, cls.underscore ] 
          end
        end
      end
    end
    opts
  end

  
  
  protected

  def set_instance_type
    self.instance_type = self.launcher_instance_type
  end
end

app/controllers/machine_blueprints_controller.rb
class MachineBlueprintsController < ApplicationController

  current_tab "M. Blueprints"
  


  # GET /machine_blueprints
  # GET /machine_blueprints.xml
  def index
    @machine_blueprints = MachineBlueprint.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @machine_blueprints }
    end
  end

  # GET /machine_blueprints/1
  # GET /machine_blueprints/1.xml
  def show
    @machine_blueprint = MachineBlueprint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @machine_blueprint }
    end
  end

  # GET /machine_blueprints/new
  # GET /machine_blueprints/new.xml
  def new
    @machine_blueprint = MachineBlueprint.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @machine_blueprint }
    end
  end

  # GET /machine_blueprints/1/edit
  def edit
    @machine_blueprint = MachineBlueprint.find(params[:id])
  end

  # POST /machine_blueprints
  # POST /machine_blueprints.xml
  def create
    @machine_blueprint = MachineBlueprint.new(params[:machine_blueprint])

    respond_to do |format|
      if @machine_blueprint.save
        format.html { 
           redirect_to(edit_machine_blueprint_url(@machine_blueprint), :notice => 'Verify Machine Parameters and Hit Submit to save.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /machine_blueprints/1
  # PUT /machine_blueprints/1.xml
  def update
    @machine_blueprint = MachineBlueprint.find(params[:id])

    respond_to do |format|
      if @machine_blueprint.update_attributes(params[:machine_blueprint])
        format.html { redirect_to(machine_blueprints_url, :notice => 'Machine blueprint was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @machine_blueprint.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /machine_blueprints/1
  # DELETE /machine_blueprints/1.xml
  def destroy
    @machine_blueprint = MachineBlueprint.find(params[:id])
    @machine_blueprint.destroy

    respond_to do |format|
      format.html { redirect_to(machine_blueprints_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/machine_blueprints_helper.rb
module MachineBlueprintsHelper
end

app/views/machine_blueprints/_form.html.haml
= semantic_form_for @machine_blueprint do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :name
    = f.input :identifier
  - if @machine_blueprint.new_record?
    = f.inputs do
      = f.input :launcher_class, :as => :select, :collection => MachineBlueprint.launcher_class_options 
  - else
    = render :partial => 'parameters'
  = f.buttons do
    = f.commit_button "Submit"

app/views/machine_blueprints/_parameters.html.haml
= semantic_fields_for 'machine_blueprint[config]', @machine_blueprint.config do |f|
  = f.inputs do
    - @machine_blueprint.parameters.each do |param|
      = f.input param[0], (param[1].is_a?(Hash) ? param[1] : param[1].call)

app/views/machine_blueprints/edit.html.haml
%h1 Editing Machine Blueprint
= render 'form'
|
= link_to 'Back', machine_blueprints_path

app/views/machine_blueprints/index.html.haml
%h1 Machine Blueprints
.action_links
  = link_to 'New Machine blueprint', new_machine_blueprint_path
%table.main_table
  %tr
    %th Identifier    
    %th Name
    %th Created
    %th Launcher
    %th Instance Type
    %th Description
    %th Destroy
  - @machine_blueprints.each do |machine_blueprint|
    %tr
      %td= link_to machine_blueprint.identifier, edit_machine_blueprint_path(machine_blueprint)
      %td= machine_blueprint.name
      %td= machine_blueprint.created_at.to_s(:short)
      %td= machine_blueprint.launcher_name
      %td= machine_blueprint.instance_type_display
      %td= machine_blueprint.launcher_description
      %td= link_to 'Destroy', machine_blueprint, :confirm => 'Are you sure?', :method => :delete
%br/

app/views/machine_blueprints/new.html.haml
%h1 New machine_blueprint
= render 'form'
= link_to 'Back', machine_blueprints_path